### ISSUE TITLE
Freeze in the new version

### ISSUE THREAD

**Issue by Durlyn** [The-Panacea-Projects/Gnomenu#101]
After updating to the latest version, there were freeze. When you turn on the extension, you need to wait 5-10 minutes for the system to react to the mouse.

**Comment by Ashleyz4** [comment]
also getting this now. Don't want to touch settings til' this is fixed cause it's super annoying.

**Comment by CrisBarreiro** [comment]
Still happening. This bug is pretty annoying, as it freezes the entire system, so every time I install it on a new machine, I have to force several reboots in order to be able to tweak everything

**Comment by The-Panacea-Projects** [comment]
Will you try logging in via Xorg as oppose to the default Wayland session and let us know if this still occurs.
